= UPLOAD_IMAGE-RESTAPI-NODEJS

== IDE

=== Visual Studio Code

==== Extensiones

Instalación en VS Code usando el Quick Open (Ctrl + P), pegue el siguiente comando y presione Entrar.

[source,shell script]
----
ext install asciidoctor.asciidoctor-vscode
ext install EditorConfig.EditorConfig
ext install esbenp.prettier-vscode
ext install mhutchie.git-graph
----
== GIT

Si usas windows y se tiene problemas con el retorno de carro (LF/CRLF) configurar este comando:

----
git config --global core.autocrlf input
----

== Comandos para correr el proyecto en dev

=== Usar Nodemon en Typescript

De manera correcta NODEMON corre codigo Javascript, pero si estas utilizando Typescript, tendras problemas y
usaras configuraciones tediosas. Una manera sencilla es usando 2 scripts en tu package.json:

*"tsc -w"* --> Transpila codigo Typescript a Javascript de manera automatica, estando atento a cambios.

*"nodemon ./build/index.js"* --> Utilizas nodemon con el codigo JS generado.

[source,shell script]
----
"ts": "tsc -w"
"dev": "nodemon ./build/index.js"
----

== ESLint y Prettier
=== Pasos para su configuración
----
1) Instalar de manera local la dependencia(modulo) ESLint
1.1) npm install eslint --save-dev || yarn add eslint --dev
2) Instalar el plugin ESLint en VSCode para su deteccion automatica de errores sin usar el comando de ESLint
3) Configurar ESLint con la ayuda del comando: 
    "npx eslint --init || yarn run eslint --init"
4) Escoger las opciones de acuerdo al proyecto que estes trabajando
5) Instalar el plugin de Prettier
6) Crear el archivo: prettierrc (en el cual colocar las opciones de formateo)
7) Es conveniente colocar en el archivo settings.json las siguientes lineas:
    // Prettier config
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "prettier.requireConfig": true
----
